// AUTO-GENERATED from marketing-brain/manifest.json — do not edit by hand.
// Regenerate after updating the knowledge base.

export type Book = {
  slug: string;
  title: string;
  author: string;
  cover: string;
  summary: string;
};

export type Video = {
  id: string;
  title: string;
  channel: string;
  views: number;
  duration: string;
  url: string;
  thumb: string;
  summary: string;
};

export type Expert = {
  slug: string;
  name: string;
  books: string[];
  videos: Video[];
};

export const books: Book[] = [
  {
    slug: "hormozi-100m-offers",
    title: "$100M Offers",
    author: "Alex Hormozi",
    cover: "/marketing-brain/book-covers/hormozi-100m-offers.jpg",
    summary: "How to build a Grand Slam Offer so good people feel stupid saying no: the value equation, pricing, scarcity, urgency, guarantees, and naming.",
  },
  {
    slug: "hormozi-100m-leads",
    title: "$100M Leads",
    author: "Alex Hormozi",
    cover: "/marketing-brain/book-covers/hormozi-100m-leads.jpg",
    summary: "How to get strangers to want to buy your stuff: the four core lead sources, lead magnets, and scaling outreach, content, and ads.",
  },
  {
    slug: "hormozi-100m-money-models",
    title: "$100M Money Models",
    author: "Alex Hormozi",
    cover: "/marketing-brain/book-covers/hormozi-100m-money-models.jpg",
    summary: "How to structure offers and payments so you get paid to acquire customers: attraction, upsell, downsell, and continuity money models.",
  },
  {
    slug: "brunson-dotcom-secrets",
    title: "DotCom Secrets",
    author: "Russell Brunson",
    cover: "/marketing-brain/book-covers/brunson-dotcom-secrets.jpg",
    summary: "The underground playbook for growing a company online: value ladders, sales funnels, traffic, and follow-up sequences.",
  },
  {
    slug: "cialdini-influence",
    title: "Influence: The Psychology of Persuasion",
    author: "Robert Cialdini",
    cover: "/marketing-brain/book-covers/cialdini-influence.jpg",
    summary: "The six (later seven) universal principles of persuasion: reciprocity, commitment/consistency, social proof, authority, liking, and scarcity.",
  },
  {
    slug: "vaynerchuk-jjjrh",
    title: "Jab, Jab, Jab, Right Hook",
    author: "Gary Vaynerchuk",
    cover: "/marketing-brain/book-covers/vaynerchuk-jjjrh.jpg",
    summary: "How to tell your story and sell in a noisy social world: give value (jabs) before you ask (right hook), with platform-native content.",
  },
  {
    slug: "ogilvy-on-advertising",
    title: "Ogilvy on Advertising",
    author: "David Ogilvy",
    cover: "/marketing-brain/book-covers/ogilvy-on-advertising.jpg",
    summary: "The advertising legend on how to write ads that sell: headlines, body copy, brand image, direct response, and research-driven creative.",
  },
  {
    slug: "godin-purple-cow",
    title: "Purple Cow",
    author: "Seth Godin",
    cover: "/marketing-brain/book-covers/godin-purple-cow.jpg",
    summary: "Be remarkable or be invisible: build something worth talking about (a Purple Cow) and market to the early adopters who spread it.",
  },
];

export const experts: Expert[] = [
  {
    slug: "hormozi",
    name: "Alex Hormozi",
    books: ["$100M Offers", "$100M Leads", "$100M Money Models"],
    videos: [
      {
        id: "x3e73Qn6NOo",
        title: "The Man That Makes Millionaires: How To Turn $1,000 Into $100 Million!: Alex Hormozi | E235",
        channel: "The Diary Of A CEO",
        views: 4785562,
        duration: "01:56:20",
        url: "https://www.youtube.com/watch?v=x3e73Qn6NOo",
        thumb: "https://i.ytimg.com/vi/x3e73Qn6NOo/maxresdefault.jpg",
        summary: "Alex Hormozi shares his journey from suicidal ideation in a corporate job to building a hundred-million-dollar business empire through pain, determination, and support.",
      },
      {
        id: "7ITff1fIbSc",
        title: "How to Grow an Audience if You Have 0 Followers",
        channel: "Alex Hormozi",
        views: 2075725,
        duration: "00:06:53",
        url: "https://www.youtube.com/watch?v=7ITff1fIbSc",
        thumb: "https://i.ytimg.com/vi/7ITff1fIbSc/maxresdefault.jpg",
        summary: "Build audience by committing to consistent daily actions for years, not expecting overnight success in 90 days.",
      },
      {
        id: "uWdIgftpvBI",
        title: "If I Started A Business in 2026, I'd Do This",
        channel: "Alex Hormozi",
        views: 1606829,
        duration: "00:18:25",
        url: "https://www.youtube.com/watch?v=uWdIgftpvBI",
        thumb: "https://i.ytimg.com/vi/uWdIgftpvBI/maxresdefault.jpg",
        summary: "Start businesses by selling expensive services to few clients or cheap products to many, avoiding the unprofitable middle market.",
      },
      {
        id: "HxEQCHpZzHk",
        title: "How to Grow Your Business SO Fast in 2026 It Feels ILLEGAL",
        channel: "Alex Hormozi",
        views: 1514675,
        duration: "01:03:08",
        url: "https://www.youtube.com/watch?v=HxEQCHpZzHk",
        thumb: "https://i.ytimg.com/vi/HxEQCHpZzHk/maxresdefault.jpg",
        summary: "Learn three core growth levers: visibility through outreach/content/ads, dominating your market instead of competing, and using clear language to maximize conversions.",
      },
      {
        id: "w7g08dVTwaE",
        title: "Watch this to get your first 5 customers",
        channel: "Alex Hormozi",
        views: 1448310,
        duration: "00:10:13",
        url: "https://www.youtube.com/watch?v=w7g08dVTwaE",
        thumb: "https://i.ytimg.com/vi/w7g08dVTwaE/maxresdefault.jpg",
        summary: "Learn a ten-step framework to acquire your first five customers by leveraging existing contacts and offering free services.",
      },
      {
        id: "RVbvhPGFi6E",
        title: "After Closing 4000+ Sales, I Discovered a New Method to Close Deals Faster",
        channel: "Alex Hormozi",
        views: 1225934,
        duration: "00:25:17",
        url: "https://www.youtube.com/watch?v=RVbvhPGFi6E",
        thumb: "https://i.ytimg.com/vi/RVbvhPGFi6E/maxresdefault.jpg",
        summary: "Learn the 3A reframing framework to control sales conversations, maintain rapport, and close deals by asking strategic questions instead of answering objections.",
      },
      {
        id: "JE2_7elAcxM",
        title: "How to Sell Better than 99% Of People (4 HOUR ULTIMATE GUIDE)",
        channel: "Alex Hormozi",
        views: 1200025,
        duration: "04:43:19",
        url: "https://www.youtube.com/watch?v=JE2_7elAcxM",
        thumb: "https://i.ytimg.com/vi/JE2_7elAcxM/maxresdefault.jpg",
        summary: "Learn logic-based sales techniques to close deals by building belief, trust, and genuine care for prospects.",
      },
      {
        id: "StVqS0jD7Ls",
        title: "The Ultimate Sales Training for 2026 [Full Course]",
        channel: "Alex Hormozi",
        views: 1089433,
        duration: "02:34:01",
        url: "https://www.youtube.com/watch?v=StVqS0jD7Ls",
        thumb: "https://i.ytimg.com/vi/StVqS0jD7Ls/maxresdefault.jpg",
        summary: "Learn six sales multipliers including selling seven days weekly, responding to leads within one minute, and optimizing scheduling to increase revenue by 29% or more.",
      },
      {
        id: "dMZ-n2KSlxE",
        title: "My Actual Social Media Strategy For 2026",
        channel: "Alex Hormozi",
        views: 791980,
        duration: "00:25:08",
        url: "https://www.youtube.com/watch?v=dMZ-n2KSlxE",
        thumb: "https://i.ytimg.com/vi/dMZ-n2KSlxE/maxresdefault.jpg",
        summary: "Learn the SPCL framework for building influence through content: Status, Power, Credibility, and Likeness stacked together.",
      },
      {
        id: "Mst4hreQYl0",
        title: "Watch This To Generate 1000s of Leads (In Any Niche)",
        channel: "Alex Hormozi",
        views: 550173,
        duration: "00:31:31",
        url: "https://www.youtube.com/watch?v=Mst4hreQYl0",
        thumb: "https://i.ytimg.com/vi/Mst4hreQYl0/maxresdefault.jpg",
        summary: "Use free lead magnets to capture more leads by solving a small problem first, then selling your core offer that solves the bigger problem.",
      },
      {
        id: "cy2k1GdA-9o",
        title: "Sales Was Hard Until I Understood These 9 Concepts",
        channel: "Alex Hormozi",
        views: 523690,
        duration: "00:51:20",
        url: "https://www.youtube.com/watch?v=cy2k1GdA-9o",
        thumb: "https://i.ytimg.com/vi/cy2k1GdA-9o/maxresdefault.jpg",
        summary: "Learn nine sales concepts that maximize opportunities, conversion rates, and consistency to build high-performing sales teams.",
      },
    ],
  },
  {
    slug: "brunson",
    name: "Russell Brunson",
    books: ["DotCom Secrets"],
    videos: [
      {
        id: "CM-RAMN_mgY",
        title: "What is a Sales Funnel? And How To Create One that Actually Makes Money",
        channel: "Russell Brunson",
        views: 415309,
        duration: "00:08:29",
        url: "https://www.youtube.com/watch?v=CM-RAMN_mgY",
        thumb: "https://i.ytimg.com/vi/CM-RAMN_mgY/maxresdefault.jpg",
        summary: "Learn how sales funnels generate profit by upselling customers, enabling you to spend more on acquisition than competitors while remaining profitable.",
      },
      {
        id: "Ip59Qbv6J_w",
        title: "Sales Funnel Strategy - 7 Simple Hacks To Get Your Sales Funnel To Convert",
        channel: "Russell Brunson",
        views: 276507,
        duration: "00:11:08",
        url: "https://www.youtube.com/watch?v=Ip59Qbv6J_w",
        thumb: "https://i.ytimg.com/vi/Ip59Qbv6J_w/maxresdefault.jpg",
        summary: "Learn seven conversion optimization tactics including curiosity headlines, lead magnets, emotional sales pages, order bumps, and upsell strategies to increase funnel profitability.",
      },
      {
        id: "8WutIx1NCNA",
        title: "Sales Funnel Explained - Sales Funnel Tutorial For Beginners (Step By Step)",
        channel: "Russell Brunson",
        views: 147895,
        duration: "00:07:07",
        url: "https://www.youtube.com/watch?v=8WutIx1NCNA",
        thumb: "https://i.ytimg.com/vi/8WutIx1NCNA/maxresdefault.jpg",
        summary: "Learn how sales funnels work by following Russell Brunson's potato gun business journey from basic product sales to profitable upsells.",
      },
      {
        id: "AbDMNSfOY6c",
        title: "How To Sell Anything to Anyone With an Irresistible Offer",
        channel: "Russell Brunson",
        views: 138091,
        duration: "00:05:10",
        url: "https://www.youtube.com/watch?v=AbDMNSfOY6c",
        thumb: "https://i.ytimg.com/vi/AbDMNSfOY6c/maxresdefault.jpg",
        summary: "Learn how to create irresistible offers by bundling value at each funnel step to increase conversions and sales.",
      },
      {
        id: "7Ho62IGz8yw",
        title: "I Asked Russel Brunson How Build A Million Dollar Funnel",
        channel: "Simon Squibb",
        views: 123838,
        duration: "00:48:11",
        url: "https://www.youtube.com/watch?v=7Ho62IGz8yw",
        thumb: "https://i.ytimg.com/vi/7Ho62IGz8yw/maxresdefault.jpg",
        summary: "Learn Russell Brunson's seven-step framework for building million-dollar funnels, starting with identifying your dream customer and understanding their needs.",
      },
      {
        id: "K7Jx8oYgbhE",
        title: "Myron Golden And Russell Brunson Reveal Secrets To Making Millions",
        channel: "Myron Golden",
        views: 103598,
        duration: "01:10:43",
        url: "https://www.youtube.com/watch?v=K7Jx8oYgbhE",
        thumb: "https://i.ytimg.com/vi/K7Jx8oYgbhE/maxresdefault.jpg",
        summary: "Learn why the economic pie myth is false and how consumption creates production in a garden economy.",
      },
    ],
  },
  {
    slug: "cialdini",
    name: "Robert Cialdini",
    books: ["Influence: The Psychology of Persuasion"],
    videos: [
      {
        id: "cFdCzN7RYbw",
        title: "Science Of Persuasion",
        channel: "Team Cialdini",
        views: 14692428,
        duration: "00:11:50",
        url: "https://www.youtube.com/watch?v=cFdCzN7RYbw",
        thumb: "https://i.ytimg.com/vi/cFdCzN7RYbw/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGFkgWShZMA8=&rs=AOn4CLDi4i9dOVkf9EYlsgmoPh1RV1M3sw",
        summary: "Learn six universal principles of persuasion: reciprocity, scarcity, authority, consistency, liking, and consensus that ethically influence decision-making.",
      },
      {
        id: "kv0sOX6Alrk",
        title: "Robert Cialdini - Science Of Persuasion",
        channel: "BigSpeak Speakers Bureau",
        views: 515616,
        duration: "00:11:54",
        url: "https://www.youtube.com/watch?v=kv0sOX6Alrk",
        thumb: "https://i.ytimg.com/vi/kv0sOX6Alrk/maxresdefault.jpg",
        summary: "Learn six universal principles of persuasion: reciprocity, scarcity, authority, consistency, liking, and consensus.",
      },
      {
        id: "e7pI5qY8cCE",
        title: "The PSYCHOLOGICAL TRICKS To Persuade & Influence ANYONE! | Robert Cialdini & Lewis Howes",
        channel: "Lewis Howes",
        views: 425372,
        duration: "01:50:28",
        url: "https://www.youtube.com/watch?v=e7pI5qY8cCE",
        thumb: "https://i.ytimg.com/vi/e7pI5qY8cCE/maxresdefault.jpg",
        summary: "Learn how reciprocity, the principle of giving first, powerfully influences people to say yes and creates obligation across all cultures.",
      },
      {
        id: "aO4RC70qU1U",
        title: "The Influence Expert: 7 Ways to Get People to Do What You Want (Even When They Don't Want To)",
        channel: "The Knowledge Project Podcast",
        views: 272330,
        duration: "01:08:46",
        url: "https://www.youtube.com/watch?v=aO4RC70qU1U",
        thumb: "https://i.ytimg.com/vi/aO4RC70qU1U/maxresdefault.jpg",
        summary: "Learn how asking for advice instead of opinions creates partners, and master reciprocation as a persuasion principle by giving value first.",
      },
      {
        id: "cILPoUtuDbQ",
        title: "How to Influence Others | Robert Cialdini | Big Think",
        channel: "Big Think",
        views: 230166,
        duration: "00:14:54",
        url: "https://www.youtube.com/watch?v=cILPoUtuDbQ",
        thumb: "https://i.ytimg.com/vi/cILPoUtuDbQ/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AH-BIAC4AOKAgwIABABGGUgZShlMA8=&rs=AOn4CLB5tSFh1XETcI6y5YSRbxbQihlfPA",
        summary: "Learn six universal principles of persuasion: reciprocity, scarcity, commitment, consensus, authority, and liking that ethically influence human behavior.",
      },
      {
        id: "JHPq4j59mgE",
        title: "Robert Cialdini Interview: Influence, The Psychology of Persuasion!",
        channel: "Joe Polish",
        views: 142862,
        duration: "00:57:09",
        url: "https://www.youtube.com/watch?v=JHPq4j59mgE",
        thumb: "https://i.ytimg.com/vi/JHPq4j59mgE/maxresdefault.jpg",
        summary: "Cialdini discusses his research on influence and persuasion principles, explaining how ethical marketing educates consumers to make informed decisions.",
      },
    ],
  },
  {
    slug: "vaynerchuk",
    name: "Gary Vaynerchuk",
    books: ["Jab, Jab, Jab, Right Hook"],
    videos: [
      {
        id: "6Wcg15FaUnU",
        title: "50 Minutes of Marketing Strategy You Can Start to Use Today | Digital Agency Expo Keynote",
        channel: "GaryVee",
        views: 1552734,
        duration: "01:03:16",
        url: "https://www.youtube.com/watch?v=6Wcg15FaUnU",
        thumb: "https://i.ytimg.com/vi/6Wcg15FaUnU/maxresdefault.jpg",
        summary: "Gary Vaynerchuk shares practical marketing strategies from bootstrapping Wine Library, emphasizing self-awareness, operational discipline, and strategic timing in business growth.",
      },
      {
        id: "EhqZ0RU95d4",
        title: "Gary Vaynerchuk: Building Personal Brand Within the Social Media Landscape - Web 2.0 Expo NY",
        channel: "O'Reilly",
        views: 1388372,
        duration: "00:15:27",
        url: "https://www.youtube.com/watch?v=EhqZ0RU95d4",
        thumb: "https://i.ytimg.com/vi/EhqZ0RU95d4/hqdefault.jpg",
        summary: "Build personal brand through passion, patience, and hustle by creating authentic content and engaging directly with your community.",
      },
      {
        id: "WyW_8kMQmJM",
        title: "Complete Social Media Marketing Strategy For 2025 | GaryVee Keynote",
        channel: "GaryVee",
        views: 640397,
        duration: "00:50:44",
        url: "https://www.youtube.com/watch?v=WyW_8kMQmJM",
        thumb: "https://i.ytimg.com/vi/WyW_8kMQmJM/maxresdefault.jpg",
        summary: "Shift from follower-based to interest-based social media marketing by posting daily videos across platforms to grow your business organically.",
      },
      {
        id: "sUvWVF28CNM",
        title: "AI is Ending the Social Media Era and What Comes Next | Gary Vee",
        channel: "Sinead Bovell",
        views: 342045,
        duration: "00:50:13",
        url: "https://www.youtube.com/watch?v=sUvWVF28CNM",
        thumb: "https://i.ytimg.com/vi/sUvWVF28CNM/maxresdefault.jpg",
        summary: "AI will disrupt social media platforms through bot consumption, voice-first interfaces, and AR glasses, shifting to new distribution formats and immersive experiences.",
      },
      {
        id: "RJ3ujlMYlus",
        title: "From Posts to Profits: A Step-by-Step Social Media Guide For Businesses | GaryVee Keynote BizX",
        channel: "GaryVee",
        views: 290097,
        duration: "00:33:57",
        url: "https://www.youtube.com/watch?v=RJ3ujlMYlus",
        thumb: "https://i.ytimg.com/vi/RJ3ujlMYlus/maxresdefault.jpg",
        summary: "B2B companies must post daily social media content on LinkedIn to build brand awareness and generate leads through AI-driven algorithms that match content to interested audiences.",
      },
      {
        id: "Sxfp-g4alNU",
        title: "How to Actually Grow Your Business Using Social Media in 2025 | Tea with GaryVee ep. 74",
        channel: "GaryVee",
        views: 200354,
        duration: "00:27:31",
        url: "https://www.youtube.com/watch?v=Sxfp-g4alNU",
        thumb: "https://i.ytimg.com/vi/Sxfp-g4alNU/maxresdefault.jpg",
        summary: "Post daily authentic content mixing personal and business topics on LinkedIn to build trust and grow your business exponentially.",
      },
      {
        id: "TDWFU_uEexc",
        title: "The Biggest Marketing Opportunity in History Is Being Ignored",
        channel: "GaryVee",
        views: 181566,
        duration: "00:19:47",
        url: "https://www.youtube.com/watch?v=TDWFU_uEexc",
        thumb: "https://i.ytimg.com/vi/TDWFU_uEexc/maxresdefault.jpg",
        summary: "Free social media platforms offer unprecedented marketing opportunities that most businesses ignore by not producing enough content consistently.",
      },
      {
        id: "Ehp0Rjl5wf4",
        title: "Social Media Is Over — This Is the Future of Content | GaryVee w/ Mick Unplugged",
        channel: "GaryVee",
        views: 147063,
        duration: "00:36:00",
        url: "https://www.youtube.com/watch?v=Ehp0Rjl5wf4",
        thumb: "https://i.ytimg.com/vi/Ehp0Rjl5wf4/maxresdefault.jpg",
        summary: "Create authentic, passionate content about your interests; algorithms now reward niche topics over follower counts, and consistency matters more than perfection.",
      },
      {
        id: "QYh-Yt_lY14",
        title: "20 Minutes Of Tactical Social Media Marketing Tips — Dominate In 2025! | Tea With GaryVee #63",
        channel: "GaryVee",
        views: 116031,
        duration: "00:23:24",
        url: "https://www.youtube.com/watch?v=QYh-Yt_lY14",
        thumb: "https://i.ytimg.com/vi/QYh-Yt_lY14/maxresdefault.jpg",
        summary: "Focus on execution quality over hours worked, balance life chapters, go live for content innovation, and commit fully to ventures you're passionate about.",
      },
      {
        id: "_TdzXnYJuSY",
        title: "Building Brand: A 2025 Social Media Marketing Strategy That Works | GaryVee w/ Forbes Talks",
        channel: "GaryVee",
        views: 114461,
        duration: "00:31:03",
        url: "https://www.youtube.com/watch?v=_TdzXnYJuSY",
        thumb: "https://i.ytimg.com/vi/_TdzXnYJuSY/maxresdefault.jpg",
        summary: "Small brands now compete globally via social media and direct-to-consumer platforms, requiring constant content creation and consumer-centric decisions over boardroom politics.",
      },
    ],
  },
  {
    slug: "ogilvy",
    name: "David Ogilvy",
    books: ["Ogilvy on Advertising"],
    videos: [
      {
        id: "hhQRH49Y54k",
        title: "The psychology of digital marketing. Rory Sutherland, Ogilvy",
        channel: "GDS Group",
        views: 855088,
        duration: "01:28:05",
        url: "https://www.youtube.com/watch?v=hhQRH49Y54k",
        thumb: "https://i.ytimg.com/vi/hhQRH49Y54k/maxresdefault.jpg",
        summary: "Behavioral economics reveals why marketing creates value differently than finance expects, through psychological innovation over pure logic.",
      },
      {
        id: "Br2KSsaTzUc",
        title: "David Ogilvy: We Sell or Else",
        channel: "OgilvyGroup01",
        views: 294502,
        duration: "00:06:59",
        url: "https://www.youtube.com/watch?v=Br2KSsaTzUc",
        thumb: "https://i.ytimg.com/vi/Br2KSsaTzUc/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AHeAoAChgKKAgwIABABGEEgZShSMA8=&rs=AOn4CLAlcU6GmZEAyi1gG8KT1hrh9treTQ",
        summary: "Direct response advertising outperforms general advertising because it's measurable and results-driven, while general advertisers rely on unmeasurable creativity and should learn from direct response professionals.",
      },
      {
        id: "0kfsnjcUNiw",
        title: "A conversation about advertising, with David Ogilvy",
        channel: "Javier Piedrahita",
        views: 151525,
        duration: "00:54:51",
        url: "https://www.youtube.com/watch?v=0kfsnjcUNiw",
        thumb: "https://i.ytimg.com/vi/0kfsnjcUNiw/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AH-AoACoAKKAgwIABABGDcgUCh_MA8=&rs=AOn4CLC3A0dVt7PHPyskwZIi5OBfyG4aBg",
        summary: "David Ogilvy shares how research-driven creative advertising built his agency into a top five firm through iconic campaigns.",
      },
      {
        id: "yj9rokSeack",
        title: "David Ogilvy: Essentials",
        channel: "ADWEEK",
        views: 151481,
        duration: "00:04:04",
        url: "https://www.youtube.com/watch?v=yj9rokSeack",
        thumb: "https://i.ytimg.com/vi/yj9rokSeack/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGH8gEygdMA8=&rs=AOn4CLAKJ6cyo8KqVJc2TbuQ8UQiw7lW2g",
        summary: "David Ogilvy shares advertising principles: be ambitious, compete with immortals, inject story appeal, tell truth fascinatingly, avoid gimmicks.",
      },
      {
        id: "sl4FjkuBPi8",
        title: "This is HOW to Dominate Advertising Industry! | David Ogilvy",
        channel: "Evan Carmichael",
        views: 117838,
        duration: "00:09:32",
        url: "https://www.youtube.com/watch?v=sl4FjkuBPi8",
        thumb: "https://i.ytimg.com/vi/sl4FjkuBPi8/maxresdefault.jpg",
        summary: "Learn David Ogilvy's three core strategies: deliver exceptional client results, continuously test campaigns, and hire talented people.",
      },
    ],
  },
  {
    slug: "godin",
    name: "Seth Godin",
    books: ["Purple Cow"],
    videos: [
      {
        id: "BPK_qzeH_yk",
        title: "Seth Godin - Everything You (probably) DON'T Know about Marketing",
        channel: "Behind the Brand",
        views: 2860756,
        duration: "00:46:35",
        url: "https://www.youtube.com/watch?v=BPK_qzeH_yk",
        thumb: "https://i.ytimg.com/vi/BPK_qzeH_yk/maxresdefault.jpg",
        summary: "Marketing is about making change for specific people by building distinct brands that stand for something, not just logos or interruption tactics.",
      },
      {
        id: "qzoIAJYPQwo",
        title: "Seth Godin – Leadership vs. Management - What it means to make a difference",
        channel: "Nordic Business Forum",
        views: 2115764,
        duration: "00:42:55",
        url: "https://www.youtube.com/watch?v=qzoIAJYPQwo",
        thumb: "https://i.ytimg.com/vi/qzoIAJYPQwo/maxresdefault.jpg",
        summary: "Leadership differs from management; leaders take responsibility and drive innovation when the world changes, while managers maintain efficient systems.",
      },
      {
        id: "xBIVlM435Zg",
        title: "How to get your ideas to spread | Seth Godin",
        channel: "TED",
        views: 2099186,
        duration: "00:18:58",
        url: "https://www.youtube.com/watch?v=xBIVlM435Zg",
        thumb: "https://i.ytimg.com/vi/xBIVlM435Zg/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AGuA4AC8AGKAgwIABABGD0gRihyMA8=&rs=AOn4CLCvbzV0rFyCZuYJqKAzWr0mk5zhYA",
        summary: "Ideas spread through remarkable, word-of-mouth appeal to passionate audiences, not through traditional interruption-based advertising.",
      },
      {
        id: "8zcnK6Lx_p4",
        title: "Marketing Godfather: How To Build An Audience That Buys (Best Hour You’ll Spend Today!) | Seth Godin",
        channel: "The Calum Johnson Show",
        views: 773983,
        duration: "00:59:02",
        url: "https://www.youtube.com/watch?v=8zcnK6Lx_p4",
        thumb: "https://i.ytimg.com/vi/8zcnK6Lx_p4/maxresdefault.jpg",
        summary: "Stop making average products and focus on creating remarkable things worth talking about instead of chasing social media algorithms.",
      },
      {
        id: "9YFNgKwv31A",
        title: "Seth Godin: Marketing Strategies That Work",
        channel: "Marie Forleo",
        views: 312124,
        duration: "00:31:11",
        url: "https://www.youtube.com/watch?v=9YFNgKwv31A",
        thumb: "https://i.ytimg.com/vi/9YFNgKwv31A/maxresdefault.jpg",
        summary: "Marketing means making meaningful change for specific people you serve, not reaching everyone through manipulation or interruption.",
      },
      {
        id: "uQGYr9bnktw",
        title: "The tribes we lead | Seth Godin",
        channel: "TED",
        views: 297575,
        duration: "00:17:23",
        url: "https://www.youtube.com/watch?v=uQGYr9bnktw",
        thumb: "https://i.ytimg.com/vi/uQGYr9bnktw/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AHQBoAC4AOKAgwIABABGFogYihlMA8=&rs=AOn4CLB4YJcmDYb6uo7V01cNqG_Q395Pgw",
        summary: "Leaders create change by building tribes of passionate people around ideas, not through factories or mass advertising.",
      },
      {
        id: "o76qx7ZzFs4",
        title: "Seth Godin: Thinking Backwards",
        channel: "CreativeMornings HQ",
        views: 279707,
        duration: "00:19:22",
        url: "https://www.youtube.com/watch?v=o76qx7ZzFs4",
        thumb: "https://i.ytimg.com/vi/o76qx7ZzFs4/maxresdefault.jpg",
        summary: "Learn how to lead upward, choose better clients, and create meaningful change through patience and storytelling rather than authority.",
      },
      {
        id: "inBvLIIcRr0",
        title: "Purple Cow, How to Be Remarkable, and the Secrets of Marketing in 2023:  with Seth Godin",
        channel: "PtexGroup",
        views: 276865,
        duration: "00:36:27",
        url: "https://www.youtube.com/watch?v=inBvLIIcRr0",
        thumb: "https://i.ytimg.com/vi/inBvLIIcRr0/maxresdefault.jpg",
        summary: "Remarkable products spread through word-of-mouth when they solve specific customer problems and tell compelling stories, not through ads or hype.",
      },
      {
        id: "zFHzTy7XLbM",
        title: "How to Build a Remarkable Brand in the Age of AI | Seth Godin",
        channel: "The Entrepreneur's Studio",
        views: 221097,
        duration: "00:37:37",
        url: "https://www.youtube.com/watch?v=zFHzTy7XLbM",
        thumb: "https://i.ytimg.com/vi/zFHzTy7XLbM/maxresdefault.jpg",
        summary: "Marketing is creating conditions for customers to spread your ideas, not spending money on ads. Trust and consistency matter more than authenticity in building remarkable brands.",
      },
      {
        id: "bHubyKHmP-U",
        title: "SETH GODIN - THIS IS MARKETING: How To Find Your Viable Audience & Win Trust From Your Target Market",
        channel: "London Real",
        views: 186428,
        duration: "00:45:44",
        url: "https://www.youtube.com/watch?v=bHubyKHmP-U",
        thumb: "https://i.ytimg.com/vi/bHubyKHmP-U/maxresdefault.jpg",
        summary: "Marketing means changing culture for the better through daily practice and discipline, not hype or promotion.",
      },
    ],
  },
  {
    slug: "ralston",
    name: "Caleb Ralston",
    books: [],
    videos: [
      {
        id: "Ch4Sl0POBhU",
        title: "How to Build a Personal Brand (Full Course)",
        channel: "Caleb Ralston",
        views: 1146862,
        duration: "06:22:27",
        url: "https://www.youtube.com/watch?v=Ch4Sl0POBhU",
        thumb: "https://i.ytimg.com/vi/Ch4Sl0POBhU/maxresdefault.jpg",
        summary: "Learn to build an intentional personal brand through strategic positioning, content consistency, and deliberate audience associations.",
      },
      {
        id: "uJ8Pg6t_iho",
        title: "How to START a Personal Brand (Full Course)",
        channel: "Caleb Ralston",
        views: 224032,
        duration: "05:05:49",
        url: "https://www.youtube.com/watch?v=uJ8Pg6t_iho",
        thumb: "https://i.ytimg.com/vi/uJ8Pg6t_iho/maxresdefault.jpg",
        summary: "Learn to build a personal brand focused on gaining customers, not just followers, by defining goals and establishing credibility.",
      },
      {
        id: "qa13iuKa8zA",
        title: "The Creative's Guide to Personal Branding (Full Playbook)",
        channel: "orenmeetsworld",
        views: 121072,
        duration: "00:35:36",
        url: "https://www.youtube.com/watch?v=qa13iuKa8zA",
        thumb: "https://i.ytimg.com/vi/qa13iuKa8zA/maxresdefault.jpg",
        summary: "Learn four levels of personal branding, five archetypes, and actionable frameworks to build your brand from beginner to advanced.",
      },
      {
        id: "mdPS9P-iHos",
        title: "How To Scale a Brand so Fast It Feels illegal w/ Caleb Ralston",
        channel: "THE 505 PODCAST ",
        views: 112018,
        duration: "01:43:42",
        url: "https://www.youtube.com/watch?v=mdPS9P-iHos",
        thumb: "https://i.ytimg.com/vi/mdPS9P-iHos/maxresdefault.jpg",
        summary: "Learn Caleb Ralston's brand journey framework to reverse engineer your desired outcome and build sustainable social strategy without copying others.",
      },
      {
        id: "wVdt8cemuDk",
        title: "If you struggle with making content, please watch this.",
        channel: "Caleb Ralston",
        views: 108873,
        duration: "00:12:04",
        url: "https://www.youtube.com/watch?v=wVdt8cemuDk",
        thumb: "https://i.ytimg.com/vi/wVdt8cemuDk/maxresdefault.jpg",
        summary: "Overcome content creation barriers by building sustainable processes, staying authentic, and focusing on value delivery rather than perfection.",
      },
    ],
  },
  {
    slug: "patel",
    name: "Neil Patel",
    books: [],
    videos: [
      {
        id: "dU4rWLHAcoo",
        title: "How to Create a Digital Product That Generates (AT LEAST) $100,000 Per Month",
        channel: "Neil Patel",
        views: 1338035,
        duration: "00:50:02",
        url: "https://www.youtube.com/watch?v=dU4rWLHAcoo",
        thumb: "https://i.ytimg.com/vi/dU4rWLHAcoo/maxresdefault.jpg",
        summary: "Learn to create and sell digital products for $100k+ monthly by choosing the right niche, building valuable products, and using effective sales funnels.",
      },
      {
        id: "Q_lySNxCag0",
        title: "SEO Unlocked: FULL Free SEO Course With Neil Patel (4+ HOURS)",
        channel: "Neil Patel",
        views: 482221,
        duration: "00:10:09",
        url: "https://www.youtube.com/watch?v=Q_lySNxCag0",
        thumb: "https://i.ytimg.com/vi/Q_lySNxCag0/maxresdefault.jpg",
        summary: "Learn SEO fundamentals, keyword research, content marketing, link building, and technical optimization to drive free organic traffic over seven weeks.",
      },
      {
        id: "hXPALnu3Y6I",
        title: "The 8 Trends I’m Betting My Entire Marketing Strategy On in 2026",
        channel: "Neil Patel",
        views: 320154,
        duration: "00:15:20",
        url: "https://www.youtube.com/watch?v=hXPALnu3Y6I",
        thumb: "https://i.ytimg.com/vi/hXPALnu3Y6I/maxresdefault.jpg",
        summary: "Eight digital marketing trends for 2026: keep leads on-platform, optimize for search everywhere, use AI intelligently, build topical authority for AI discovery, prepare for identity-based AI ads, adapt to browser-based AI platforms, and leverage live content.",
      },
      {
        id: "ybttlXsLPXc",
        title: "If I Wanted to Become a Millionaire in 12 Months, This is What I’d Do",
        channel: "Neil Patel",
        views: 319446,
        duration: "00:15:22",
        url: "https://www.youtube.com/watch?v=ybttlXsLPXc",
        thumb: "https://i.ytimg.com/vi/ybttlXsLPXc/maxresdefault.jpg",
        summary: "Build long-term audience ownership through content and SEO to generate consistent website traffic and monetize at scale.",
      },
      {
        id: "pIbQfOcsEsE",
        title: "The ONLY Video You Need To Understand SEO",
        channel: "Neil Patel",
        views: 314318,
        duration: "00:10:29",
        url: "https://www.youtube.com/watch?v=pIbQfOcsEsE",
        thumb: "https://i.ytimg.com/vi/pIbQfOcsEsE/maxresdefault.jpg",
        summary: "Learn why SEO matters, how Google dominates search, and the key ranking factors that drive traffic and sales.",
      },
      {
        id: "39o0uYPo4jU",
        title: "The New Rules of SEO (2026)",
        channel: "Neil Patel",
        views: 273537,
        duration: "00:11:54",
        url: "https://www.youtube.com/watch?v=39o0uYPo4jU",
        thumb: "https://i.ytimg.com/vi/39o0uYPo4jU/maxresdefault.jpg",
        summary: "Consumers decide across TikTok, Reddit, Amazon, and ChatGPT, not Google. Optimize for decision moments on multiple platforms to stay visible.",
      },
      {
        id: "6RNJpItArSQ",
        title: "It Took Me Years to Learn Digital Marketing, But You Can Learn it in 13 Minutes",
        channel: "Neil Patel",
        views: 234635,
        duration: "00:09:31",
        url: "https://www.youtube.com/watch?v=6RNJpItArSQ",
        thumb: "https://i.ytimg.com/vi/6RNJpItArSQ/maxresdefault.jpg",
        summary: "Learn digital marketing fundamentals: test content on X, start a blog, optimize conversions with heatmaps, use AI strategically, and continuously iterate.",
      },
      {
        id: "3x9AWh7g1YQ",
        title: "7 Social Media Hacks That’ll Make Your Business Grow Faster | Neil Patel",
        channel: "Neil Patel",
        views: 209618,
        duration: "00:06:51",
        url: "https://www.youtube.com/watch?v=3x9AWh7g1YQ",
        thumb: "https://i.ytimg.com/vi/3x9AWh7g1YQ/maxresdefault.jpg",
        summary: "Learn seven social media strategies to boost engagement, reach, and sales across Facebook, Instagram, LinkedIn, and Twitter.",
      },
      {
        id: "bfA6GAk7_WQ",
        title: "How To Train Google’s AI to Send You Customers",
        channel: "Neil Patel",
        views: 193353,
        duration: "00:12:18",
        url: "https://www.youtube.com/watch?v=bfA6GAk7_WQ",
        thumb: "https://i.ytimg.com/vi/bfA6GAk7_WQ/maxresdefault.jpg",
        summary: "Learn how to optimize content for Google's AI to get cited in search results and build brand authority beyond traditional rankings.",
      },
      {
        id: "5-51beM596o",
        title: "$100M Worth of Brand New Marketing Strategies for 2025",
        channel: "Neil Patel",
        views: 107742,
        duration: "00:13:52",
        url: "https://www.youtube.com/watch?v=5-51beM596o",
        thumb: "https://i.ytimg.com/vi/5-51beM596o/maxresdefault.jpg",
        summary: "Learn 2025 marketing strategies: go omni-channel, expand search beyond Google, build recognizable brands, optimize checkout, think globally, hire experienced talent, and test rapidly.",
      },
    ],
  },
  {
    slug: "mrbeast",
    name: "MrBeast",
    books: [],
    videos: [
      {
        id: "c8VcUnz3nVc",
        title: "The Full Story of MrBeast",
        channel: "Colin and Samir",
        views: 22568377,
        duration: "01:55:31",
        url: "https://www.youtube.com/watch?v=c8VcUnz3nVc",
        thumb: "https://i.ytimg.com/vi/c8VcUnz3nVc/maxresdefault.jpg",
        summary: "MrBeast discusses his journey from bedroom creator to building a $10M studio, staying in his hometown, reinvesting all earnings into content, and starting with small giveaways.",
      },
      {
        id: "T7M3PpjBZzw",
        title: "How I Get Over 100,000,000 Views Per Video",
        channel: "MrBeast 2",
        views: 7546581,
        duration: "00:08:09",
        url: "https://www.youtube.com/watch?v=T7M3PpjBZzw",
        thumb: "https://i.ytimg.com/vi/T7M3PpjBZzw/maxresdefault.jpg",
        summary: "MrBeast launches views.com, a platform with free and premium tools for analyzing YouTube analytics, thumbnails, and viral video trends.",
      },
      {
        id: "3A8kawxMOcQ",
        title: "How Mr. Beast Became Successful on YouTube",
        channel: "PowerfulJRE",
        views: 6832550,
        duration: "00:14:57",
        url: "https://www.youtube.com/watch?v=3A8kawxMOcQ",
        thumb: "https://i.ytimg.com/vi/3A8kawxMOcQ/maxresdefault.jpg",
        summary: "MrBeast shares his decade-long YouTube journey from age 11, emphasizing obsessive daily study of video mechanics and collaboration with other creators.",
      },
      {
        id: "09wcDevb1q4",
        title: "MrBeast being a YouTube Genius for 10 minutes straight",
        channel: "Marcus Jones",
        views: 5669785,
        duration: "00:09:54",
        url: "https://www.youtube.com/watch?v=09wcDevb1q4",
        thumb: "https://i.ytimg.com/vi/09wcDevb1q4/maxresdefault.jpg",
        summary: "MrBeast reveals YouTube success secrets: obsessive study of thumbnails, retention, audience expectations, and relentless effort over years.",
      },
      {
        id: "9DBJXRy5dvk",
        title: "MrBeast Shares His Best YouTube Advice",
        channel: "Think Media",
        views: 3806874,
        duration: "00:19:26",
        url: "https://www.youtube.com/watch?v=9DBJXRy5dvk",
        thumb: "https://i.ytimg.com/vi/9DBJXRy5dvk/maxresdefault.jpg",
        summary: "MrBeast reveals YouTube growth secrets: make 100 videos improving each, hook viewers in first 5 seconds, and prioritize audience psychology over algorithm.",
      },
      {
        id: "IXEewFEDieU",
        title: "Why every MrBeast video gets 200M views (interview)",
        channel: "Jon Youshaei",
        views: 3594963,
        duration: "01:25:45",
        url: "https://www.youtube.com/watch?v=IXEewFEDieU",
        thumb: "https://i.ytimg.com/vi/IXEewFEDieU/maxresdefault.jpg",
        summary: "MrBeast reveals his six-year internal analytics tool for finding viral video ideas and launches ViewStats Pro to help creators optimize content.",
      },
      {
        id: "X2huNCHDwMQ",
        title: "Genius YouTube Advice for 15 Minutes Straight...",
        channel: "Think Media",
        views: 1633167,
        duration: "00:15:47",
        url: "https://www.youtube.com/watch?v=X2huNCHDwMQ",
        thumb: "https://i.ytimg.com/vi/X2huNCHDwMQ/maxresdefault.jpg",
        summary: "Learn YouTube success strategies from top creators: make 100 videos improving each time, let your niche emerge naturally, use curiosity-driven titles, and focus on audience connections over vanity metrics.",
      },
      {
        id: "AX3dEGjBg6w",
        title: "Meet MrBeast's Secret YouTube Consultant (Paddy Galloway Interview)",
        channel: "Jon Youshaei",
        views: 790566,
        duration: "00:19:56",
        url: "https://www.youtube.com/watch?v=AX3dEGjBg6w",
        thumb: "https://i.ytimg.com/vi/AX3dEGjBg6w/maxresdefault.jpg",
        summary: "YouTube consultant Paddy Galloway reveals algorithm secrets and content strategies he used with MrBeast and top creators.",
      },
      {
        id: "L4rXidEr248",
        title: "How MrBeast Made YouTube’s Greatest Video (Genius Strategy)",
        channel: "Paddy Galloway",
        views: 540447,
        duration: "00:09:25",
        url: "https://www.youtube.com/watch?v=L4rXidEr248",
        thumb: "https://i.ytimg.com/vi/L4rXidEr248/maxresdefault.jpg",
        summary: "MrBeast combines retention mastery, clickbait thumbnails, and strategic financing to create YouTube's most viral videos.",
      },
      {
        id: "xavOSgdg8Zs",
        title: "1 Hour Mega Compilation of MrBeast YouTube Advice",
        channel: "Bakslash",
        views: 427926,
        duration: "01:04:58",
        url: "https://www.youtube.com/watch?v=xavOSgdg8Zs",
        thumb: "https://i.ytimg.com/vi/xavOSgdg8Zs/maxresdefault.jpg",
        summary: "MrBeast shares YouTube success strategies: stop overthinking, upload consistently, obsess over quality, study audience psychology, and reinvest everything.",
      },
      {
        id: "8XSssH3B_Dk",
        title: "The YouTube Playbook in 37 Minutes",
        channel: "Colin and Samir",
        views: 276083,
        duration: "00:37:53",
        url: "https://www.youtube.com/watch?v=8XSssH3B_Dk",
        thumb: "https://i.ytimg.com/vi/8XSssH3B_Dk/maxresdefault.jpg",
        summary: "Learn MrBeast's YouTube strategy: ideation, titles, thumbnails, audience focus, channel launches, video structure, and systemized content frameworks.",
      },
      {
        id: "5wvmDSMH9AM",
        title: "I Watched Every MrBeast Interview (here's his top YouTube advice)",
        channel: "Aprilynne Alter",
        views: 265758,
        duration: "00:27:07",
        url: "https://www.youtube.com/watch?v=5wvmDSMH9AM",
        thumb: "https://i.ytimg.com/vi/5wvmDSMH9AM/maxresdefault.jpg",
        summary: "Learn MrBeast's YouTube strategies for ideation, titles, thumbnails, hooks, and video retention from compiled interview advice.",
      },
    ],
  },
];

export const stats = {
  experts: 9,
  books: 8,
  videos: 75,
  totalViews: 109722380,
};
