// BM25 retrieval over the Marketing Brain corpus.
//
// Faithful TypeScript port of marketing-brain/scripts/query.py: same stopword
// list, tokenizer, BM25 params, and snippet extraction. The index is built once
// per process and cached in module scope, so warm serverless invocations are fast.
//
// chunks.json is read from disk (not statically imported) to keep TypeScript from
// inferring a ~9MB literal type. next.config.ts adds it to outputFileTracingIncludes
// so it ships with the /api/marketing-brain/chat function on Vercel.

import fs from "fs";
import path from "path";
import type { Chunk, Source } from "./types";
import qualityScores from "./quality-scores.json";

const STOP = new Set(
  ("a an the of to in is it for and or but on with as at by from this that " +
    "you your i we they he she them his her our my me do does so if then than " +
    "be been being are was were will would can could should how what why when " +
    "who which there here not no yes get got just like very really about into " +
    "out up down over under more most some any all one two")
    .split(" "),
);

function tok(s: string): string[] {
  const out: string[] = [];
  const matches = s.toLowerCase().match(/[a-z0-9]+/g);
  if (!matches) return out;
  for (const w of matches) {
    if (w.length > 1 && !STOP.has(w)) out.push(w);
  }
  return out;
}

// Fold each chunk's identity (book: title + author; video: title + expert) into
// the searchable text so a source is matchable by its name and creator
// (e.g. "Influence" / "Cialdini"), not only by body prose.
function indexText(chunk: Chunk): string {
  if (chunk.type === "book") {
    return `${chunk.title} ${chunk.author} ${chunk.text}`;
  }
  return `${chunk.title} ${chunk.expert} ${chunk.text}`;
}

// Unique source key: collapse near-duplicate chunks from the same book/video.
function sourceKey(chunk: Chunk): string {
  return chunk.type === "book" ? chunk.slug : chunk.videoId;
}

// Per-source quality scores live in quality-scores.json (generated by
// marketing-brain/scripts/build-quality-scores.py): books 8-10 by authority,
// videos 2-7 by view count + depth. Every video is rated individually.
const BOOK_SCORES: Record<string, number> = qualityScores.books;
const VIDEO_SCORES: Record<string, number> = qualityScores.videos;
const DEFAULT_BOOK_SCORE = 8;
const DEFAULT_VIDEO_SCORE = 4;

// Ranking model: relevance-first, with a quality PRIOR added on (not multiplied).
// final = (BM25 / maxBM25 for this query) + BETA * qualityPrior(chunk).
//
// Why additive, not a flat "books are 5x" multiplier: a multiplier lets a book
// that only weakly matches leapfrog the single best video (e.g. a generic
// offers book hijacking a "MrBeast thumbnails" question). Normalizing relevance
// to [0,1] and ADDING a quality bonus means a clearly on-topic source still
// wins, while the bonus decides near-ties and lifts books when they're genuinely
// competitive. Tuned against 20 diverse scenarios (sim-ranking-policies.py):
// this scored 19/20 ideal-mix vs ~14/20 for the best multiplicative variant.
//
// Books get a strong prior (0.90-1.00) so they lead timeless/principle topics;
// videos get a smaller, view-graded prior (0.00-0.40) so the most-watched clip
// wins among videos but a book still outranks it when relevance is close.
const BETA = 0.35;

function qualityPrior(chunk: Chunk): number {
  if (chunk.type === "book") {
    const s = Math.min(10, Math.max(8, BOOK_SCORES[chunk.slug] ?? DEFAULT_BOOK_SCORE));
    return 0.9 + ((s - 8) / 2) * 0.1; // 0.90 … 1.00
  }
  const s = Math.min(7, Math.max(2, VIDEO_SCORES[chunk.videoId] ?? DEFAULT_VIDEO_SCORE));
  return ((s - 2) / 5) * 0.4; // 0.00 … 0.40
}

// Guarantee at least this many videos in the result, so the best clips are never
// fully buried by books and mixed topics stay genuinely blended.
const RESERVE_VIDEOS = 2;

type Indexed = {
  chunk: Chunk;
  tokens: string[];
  tf: Map<string, number>;
};

type Index = {
  docs: Indexed[];
  idf: Map<string, number>;
  avgdl: number;
  inv: Map<string, number[]>; // term -> doc indices
};

let cached: Index | null = null;

function load(): Index {
  if (cached) return cached;

  const file = path.join(
    process.cwd(),
    "src/app/marketing-brain/_data/chunks.json",
  );
  const raw = JSON.parse(fs.readFileSync(file, "utf8")) as { chunks: Chunk[] };
  const chunks = raw.chunks;

  const docs: Indexed[] = [];
  const df = new Map<string, number>();
  const inv = new Map<string, number[]>();
  let totalLen = 0;

  chunks.forEach((chunk, i) => {
    const tokens = tok(indexText(chunk));
    const tf = new Map<string, number>();
    for (const w of tokens) tf.set(w, (tf.get(w) ?? 0) + 1);
    docs.push({ chunk, tokens, tf });
    totalLen += tokens.length;
    for (const w of tf.keys()) {
      df.set(w, (df.get(w) ?? 0) + 1);
      const list = inv.get(w);
      if (list) list.push(i);
      else inv.set(w, [i]);
    }
  });

  const N = docs.length;
  const idf = new Map<string, number>();
  for (const [w, d] of df) {
    idf.set(w, Math.log(1 + (N - d + 0.5) / (d + 0.5)));
  }

  cached = { docs, idf, avgdl: totalLen / Math.max(N, 1), inv };
  return cached;
}

const K1 = 1.5;
const B = 0.75;
// Max chunks taken from any single source (book slug / video id) per query, so
// near-duplicate same-source chunks can't crowd out other relevant material.
const PER_SOURCE = 2;

export function search(query: string, k = 6): Chunk[] {
  const idx = load();
  const qt = tok(query);
  if (qt.length === 0) return [];

  const cand = new Set<number>();
  for (const w of qt) {
    const list = idx.inv.get(w);
    if (list) for (const i of list) cand.add(i);
  }

  // 1. Raw BM25 relevance per candidate, tracking the per-query max for normalization.
  const raw: Array<{ raw: number; i: number }> = [];
  let maxRaw = 0;
  for (const i of cand) {
    const doc = idx.docs[i];
    const dl = doc.tokens.length || 1;
    let s = 0;
    for (const w of qt) {
      const f = doc.tf.get(w);
      if (f) {
        const idfw = idx.idf.get(w) ?? 0;
        s += (idfw * (f * (K1 + 1))) / (f + K1 * (1 - B + (B * dl) / idx.avgdl));
      }
    }
    if (s > 0) {
      raw.push({ raw: s, i });
      if (s > maxRaw) maxRaw = s;
    }
  }
  if (raw.length === 0) return [];

  // 2. Final score = normalized relevance + quality prior (see BETA / qualityPrior).
  const scoreByIdx = new Map<number, number>();
  const scored = raw.map(({ raw: r, i }) => {
    const score = r / maxRaw + BETA * qualityPrior(idx.docs[i].chunk);
    scoreByIdx.set(i, score);
    return { score, i };
  });
  scored.sort((a, b) => b.score - a.score);

  // 3. Take top `k`, allowing at most PER_SOURCE chunks per source so near-duplicate
  // same-source chunks can't monopolize the slots.
  const isVideo = (i: number) => idx.docs[i].chunk.type === "video";
  const picked: number[] = [];
  const perKey = new Map<string, number>();
  const bump = (i: number) => {
    const key = sourceKey(idx.docs[i].chunk);
    perKey.set(key, (perKey.get(key) ?? 0) + 1);
  };
  for (const { i } of scored) {
    const key = sourceKey(idx.docs[i].chunk);
    if ((perKey.get(key) ?? 0) >= PER_SOURCE) continue;
    bump(i);
    picked.push(i);
    if (picked.length >= k) break;
  }

  // 4. Guarantee at least RESERVE_VIDEOS videos: pull the next-best videos in and
  // drop the lowest-ranked books to make room, so the best clips are never buried.
  let videoCount = picked.filter(isVideo).length;
  if (videoCount < RESERVE_VIDEOS) {
    const have = new Set(picked);
    const extra: number[] = [];
    for (const { i } of scored) {
      if (videoCount + extra.length >= RESERVE_VIDEOS) break;
      if (!isVideo(i) || have.has(i)) continue;
      const key = sourceKey(idx.docs[i].chunk);
      if ((perKey.get(key) ?? 0) >= PER_SOURCE) continue;
      bump(i);
      extra.push(i);
      have.add(i);
    }
    if (extra.length) {
      const books = picked.filter((i) => !isVideo(i));
      const drop = new Set(books.slice(-extra.length)); // lowest-ranked books
      const kept = picked.filter((i) => !drop.has(i)).concat(extra);
      kept.sort((a, b) => (scoreByIdx.get(b) ?? 0) - (scoreByIdx.get(a) ?? 0));
      return kept.slice(0, k).map((i) => idx.docs[i].chunk);
    }
  }

  return picked.map((i) => idx.docs[i].chunk);
}

// Extract a short, query-centered quote (<= `width` words); mirrors query.py snippet().
function snippet(text: string, query: string, width = 24): string {
  const qt = new Set(tok(query));
  const words = text.split(/\s+/);
  const norm = (w: string) => w.toLowerCase().replace(/[^a-z0-9]/g, "");
  let best = -1;
  let bi = 0;
  for (let i = 0; i < words.length; i++) {
    if (qt.has(norm(words[i]))) {
      let win = 0;
      for (let j = i; j < Math.min(i + width, words.length); j++) {
        if (qt.has(norm(words[j]))) win++;
      }
      if (win > best) {
        best = win;
        bi = i;
      }
    }
  }
  const start = Math.max(0, bi - 6);
  const slice = words.slice(start, start + width).join(" ");
  return (start > 0 ? "…" : "") + slice + (start + width < words.length ? "…" : "");
}

// Turn retrieved chunks into client-facing Source cards (with short quotes).
export function toSources(chunks: Chunk[], query: string): Source[] {
  return chunks.map((c, idx) => {
    const n = idx + 1;
    const quote = snippet(c.text, query);
    if (c.type === "book") {
      return {
        n,
        type: "book",
        title: c.title,
        attribution: c.author,
        quote,
        page: c.page,
        cover: c.cover,
      };
    }
    return {
      n,
      type: "video",
      title: c.title,
      attribution: c.channel ? `${c.expert} · ${c.channel}` : c.expert,
      quote,
      videoId: c.videoId,
      timecode: c.timecode,
      seconds: c.seconds,
      url: c.url,
      thumb: c.thumb,
    };
  });
}
